
services:
  terraform:
    container_name: terraform
    image: hashicorp/terraform:latest
    entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - type: bind
        source: .
        target: /conf/
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION